spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_eb3ec026f66e354?reconnect=true
    username: bbd1ca985a75ae
    password: b3270a98

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true