spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livecode?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true